# Generated by Django 4.1.5 on 2023-03-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MathExpression',
            new_name='MathExp',
        ),
    ]
