# Generated by Django 4.1.5 on 2023-04-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_numsysexp_delete_mathexp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numsysexp',
            name='initial_ss',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='numsysexp',
            name='next_ss',
            field=models.IntegerField(default=0),
        ),
    ]
