# Generated by Django 4.1.5 on 2023-04-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_mathexp_delete_numsysexp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mathexp',
            name='dt',
        ),
    ]
