# Generated by Django 4.1.5 on 2023-04-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_remove_mathexp_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathexp',
            name='dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
