# Generated by Django 4.2 on 2023-05-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_mathexp_dt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MathExp',
            new_name='NumSysExp',
        ),
        migrations.AlterModelOptions(
            name='numsysexp',
            options={'verbose_name': 'пример', 'verbose_name_plural': 'примеры'},
        ),
    ]
