# Generated by Django 4.2 on 2023-05-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_rename_mathexp_numsysexp_alter_numsysexp_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('express', models.CharField(default='0', max_length=50)),
                ('res', models.IntegerField(default=0)),
                ('dt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'пример',
                'verbose_name_plural': 'примеры',
            },
        ),
        migrations.AlterModelOptions(
            name='numsysexp',
            options={'verbose_name': 'пример систем счисления', 'verbose_name_plural': 'примеры систем счисления'},
        ),
    ]
