# Generated by Django 4.2 on 2023-05-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_mathexp_alter_numsysexp_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathexp',
            name='res',
            field=models.CharField(default='0', max_length=25),
        ),
    ]
