# Generated by Django 4.2 on 2023-05-09 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_appeal_coment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='to_phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.appeal', to_field='phone', verbose_name='Телефон заявителя'),
        ),
    ]
